name: Generate the ASCII artwork

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: check workflow
        uses: actions/checkout@v4

      - name: Install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for a cover, i'm DRAGON....RAWR" >> dragon.txt

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

      - name: Read file
        run: cat dragon.txt
      
      - name: List repo file
        run: ls -ltra
 
